# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnnamedCli < Formula
  desc ""
  homepage "https://github.com/duong-vo/unnamed-cli"
  version "0.1.5"

  on_macos do
    url "https://github.com/duong-vo/unnamed-cli/releases/download/v0.1.5/unnamed-cli_0.1.5_darwin_all.tar.gz"
    sha256 "2d6dbd5928c6c18a785a40abc1dddc61199b5e0a8ec4ef2d0ce30ed15e2b65e1"

    def install
      bin.install "unnamed-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duong-vo/unnamed-cli/releases/download/v0.1.5/unnamed-cli_0.1.5_linux_arm64.tar.gz"
      sha256 "8863dd91defa2f0c25e1dcd5dd992f77039e68593cbfdd0dad29b75011e845e3"

      def install
        bin.install "unnamed-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duong-vo/unnamed-cli/releases/download/v0.1.5/unnamed-cli_0.1.5_linux_amd64.tar.gz"
      sha256 "d16fffe85e3352a13ea9b8f710d0039c1462b5d8955bb17e5ea95b5584b25a44"

      def install
        bin.install "unnamed-cli"
      end
    end
  end
end
