# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnnamedCli < Formula
  desc ""
  homepage "https://github.com/duong-vo/unnamed-cli"
  version "0.1.4"

  on_macos do
    url "https://github.com/duong-vo/unnamed-cli/releases/download/v0.1.4/unnamed-cli_0.1.4_darwin_all.tar.gz"
    sha256 "fe468cc2d6444f9a20855b32d709677f16a92b0df5db65339b2e3a01b90b39ed"

    def install
      bin.install "unnamed-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duong-vo/unnamed-cli/releases/download/v0.1.4/unnamed-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "083faafa1230d40c6e6fb9b0aa359146c3a6bc943f865ceb8ffe576fb1227eab"

      def install
        bin.install "unnamed-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duong-vo/unnamed-cli/releases/download/v0.1.4/unnamed-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "4efcbbc2a2d215c1c84010ba6b5179b48ae3682cf5c99f2325d513fcbd19ddf2"

      def install
        bin.install "unnamed-cli"
      end
    end
  end
end
